[package]
name = "tantivy-jieba"
version = "0.4.0"
authors = ["Jiajie Chen <noc@jiegec.ac.cn>"]
edition = "2018"
description = "A library that bridges between tantivy and jieba-rs"
repository = "https://github.com/jiegec/tantivy-jieba"
readme = "README.md"
keywords = ["tantivy", "jieba"]
license = "MIT"

[dependencies]
tantivy = "0.13.2"
jieba-rs = "0.6.1"
lazy_static = "1.4.0"
